### ISSUE TITLE
Как сделать бекап с удаленного хоста

### ISSUE THREAD

**Issue by CrashX** [keygenqt/backupz#2]
А как выполнять бекап с удаленного хоста?

config
```
backup:
  - /var/www/mysite

execute: []

exclude: []

compression: best

name: 'backupz_%d_%m_%Y'

folder: /backup/mysite

ssh: [{
 hostname: '11.22.33.44',
 username: 'root',
 port: '22',
 auth: 'pa55wd'
}]

ftp: []
```
Получаю No file or directory found along the path:  /var/www/mysite

**Comment by keygenqt** [comment]
ssh для заливки готового бекапа. С удаленного можно по http например.

Array folders SSH for save -> https://keygenqt.github.io/backupz/using/config

**Comment by CrashX** [comment]
К сожалению, это не вариант
если возможно добавить функционал то было б замечательно
Примерное описание
- на сервере бекапов создаем задание с выполнением на удаленном сервере
те бекап сервер подключается к удаленной консоли и выполняет архивацию, затем тащит к себе бекап

настройка аналогичного сервиса на стороне клиента не является безопасной

**Comment by keygenqt** [comment]
Если на сервере нужно сделать бекап то мы можем поставить приложение туда и создавать бекапы. Скачать их от туда не является задачей для приложения.

Например у нас 2 сервера: на первом крутятся сайты, на втором хранятся бекапы. Логика следующая: на первом создаем бекап с помощью приложения, а на второй он загружается.

**Comment by CrashX** [comment]
> Например у нас 2 сервера: на первом крутятся сайты, на втором хранятся бекапы. Логика следующая: на первом создаем бекап с помощью приложения, а на второй он загружается.

Проблема в безопасности, сервер с сайтами имеет доступ к серверу с бекапами.
Да можно создать изолированного пользователя, но это не решит проблему с доступом ко всем бекапам с сервера где сайты.

А теперь возьмем что серверов с сайтами 10-20-100, и тут наступает проблема #2 
не возможность централизованного управления.

Пробовали rdiff - умеет ходить на удаленные сервера и тащить к себе, минус - это rsync пусть и более продуманный, нет возможности делать именно архивы
Так же смотрю на restic смущает идеология хранилища, аля svn в мануалах вижу частое упоминание о возможных поломках хранилища... а когда проекты по 30-50 гб...


Ваш вариант очень интересен тем что там можно указать набор команд для выполнения, те нет привязки к методу и архиватору можно заюзать тот же pigz + tar, но не могу придумать как тащить бекапы на сервер бекапов и делать это централизованно со стороны сервера где хранятся бекапы

**Comment by keygenqt** [comment]
Я не думаю что на серверах нужно бекапы делать YouTube & Telegram. Все же думаю что это больше прикладное приложение, без задачи бекапить 100 серверов со стороннего сервера. Усложнять можно, но на это время нужно, которого к сожалению мало. На данный момент я покрыл основные задачи которые ставил перед приложением. Это же open-source, всегда можно форкнуть и доработать.

**Comment by CrashX** [comment]
Понял спасибо
